### ISSUE TITLE
searching filia

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#10]
searching filia in the advanced search I get this

Error parsing you request!
Please report this bug at https://github.com/EAGLE-BPN/Inscription-Search-Engine

**Comment by PietroLiuzzo** [comment]
Same error with basic search. I have tried all fields, it is not possible to run any search

**Comment by cprando** [comment]
This was a problem with the SOLR index which was not available due to a problem of the server at CNR. Now the server is again available.
