### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#16]
The link to view translations shows only one random translation out the many avaialble. 
See HD024262 + IRT474 where only the german translation available at http://www.eagle-network.eu/wiki/index.php/Item:Q538 is listed. there are also two english and an italian translation

**Comment by cprando** [comment]
Implemented

**Comment by PietroLiuzzo** [comment]
The translations are all viewed, as simple text. an indication of the language would be useful. e.g.

DE : Unserem Herrn Gratian, dem frommen, vom Glück gesegneten, dem Sieger und Triumphator, dem immerwährenden Augustus. Die Bürger von Lepcis (Leptitani), seinem göttlichen Wesen und seiner Majestät ergeben, [errichteten dieses Denkmal].
EN: To our lord Gratian, emperor, victor and triumphator, always Augustus; the Leptitanians, devoted to his divine power and majesty [set this up].
EN 2: To our lord Gratian, pious, fortunate, victorious and triumphant, forever Augustus. The people of Lepcis (Leptitani), devoted to his divine spirit and majesty, [set this up].
IT: Al nostro signore Graziano, Pio Felice vincitore e trionfatore, per sempre Augusto, i Leptitani devoti al suo nume e alla sua maestà (posero).

**Comment by francescomambrini** [comment]
It seems to be working correctly now
