### ISSUE TITLE
the Greek keyboard does not support polytonic Greek

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#2]
The Greek keyboard that is loaded after a user select to "enable polytonic" is in fact for monotonic Greek, not polytonic

**Comment by cprando** [comment]
Changed to "Greek keyboard"

**Comment by cprando** [comment]
I reopen this issue as enhancement just to remember that we could integrate a polytonic keyboard as a future improvement

**Comment by cprando** [comment]
Integrated Greek Polytonic and Hebrew keyboards
