### ISSUE TITLE
search problem

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#20]
se cerco il testo Nonio Marci, trovo alcune iscrizioni; se voglio restringere la scelta cercando il testo Nonio Marci filio ottengo la risposta "no results", mentre tra i risultati della ricerca precedente c'erano numerose iscrizioni con "Nonio Marci filio". Dove sta il problema? Ho solo allungato la stringa di caratteri da cercare...

**Comment by PietroLiuzzo** [comment]
per 'nonio marci filio' trovo da basic search 24614 risultati
per nonio marci trovo da basic search 9477

puzzling...

**Comment by cprando** [comment]
E' corretto così.
Attenzione perchè - come tutte le ricerche per testo libero - di default la basic search funziona concatenando i termini in "OR".
Qundi cercando Nonio Marci si cercano tutte le epigrafi che contengono "Nonio" OPPURE "Marci" (che sono 9477).
Cercando Ninio Marci filio si ottengono tutte le epigrafi che contengono "Nonio" OPPURE "Marci" OPPURE "filio" (che sono ovviamente di più: 24614).
Se si vuole cercare tutte le epigrafi che contengono la stringa esatta Nonio Marci (o qualsiasi altra) vanno messe le virgolette: "Nonio Marci". In questo caso ad es. ottengo 19 risultati.
RIcordiamoci infine che la ricerca per diacritici ancora non è implementata e quindi le parentesi vanno indicate nella stringa di ricerca altrimenti non si ottengono risultati. Ecco dunque che se cerco la stringa esatta "Nonio Marci filio" non ho risultati. Se cerco invece "Nonio M(arci) f(ilio)" ne ottengo 18.
