### ISSUE TITLE
numero fornito per i risultati

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#21]
Il numero fornito per i risultati di una ricerca è molto poco utile. intanto per via dell'about. immagino che il numero sia esatto. il motore trova 24 risultati. ora data la natura dei di EAGLE dovremmo cercare credo di essere più precisi e dire per esempio in quelli sintesi: "Sono stati trovati in tutto 24 risultati. Di questi 12 sono testi, e 10 hanno un identificatore univoco. le altre sono immagini collegate a questi testi"

**Comment by cprando** [comment]
Fixed
