### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#22]
Silvia (e W. Eck) riportano che registrandosi si riceve un messaggio che invita ad aspettare una password che però non arriva mai.

**Comment by PietroLiuzzo** [comment]
<img width="399" alt="schermata 2015-12-05 alle 15 36 44" src="https://cloud.githubusercontent.com/assets/508012/11608606/10a4df0a-9b66-11e5-9f51-08cf9269bfd7.png">
Does it mean until someone has time to act upon a registration users cannot do anything? this is not a very common behaviour on websites now a days. verification emails should be sent and the process should be resolved in matter of minutes

**Comment by cprando** [comment]
Corretto, attualmente è necessariamente così perchè - anche se il Portale è stato reso pubblico - stiamo sempre parlando di un prototipo e non posso dare accesso automaticajmente a tutte le registrazioni senza verificarle di persona per motivi di sicurezza.
Quindi le registrazioni devono essere approvate manualmente da un ammisiatratore.
Quando poi il server sarà migrato a Sapienza naturalmente questa policy potrà senz'altro cambiare.
