### ISSUE TITLE
filtri & facet

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#23]
da Silvia Evangelisti

Se da un esito di ricerca vado al particolare della scheda non funziona il Back to result list se lo uso più di una volta. La prima volta funziona, se riapro e ritorno alla Back to list non funziona più.

Se dalla ricerca di base (Cerco Milano) vado a tentare di raffinare la ricerca, mi pare che non funzioni se non il primo filtro (anche qui la prima volta che applico il filtro funziona poi non più). Per la cronaca il filtro decoration è ancora incomprensibile.

Dalla ricerca di base ottengo 3076 risultati. Applico ad esempio il filtro Altar e ottengo correttamente i 420 risultati. Aggiungo il filtro honorarius riapplico e non funziona. Quindi come per il back to result list funziona solo la prima volta che effettuo la ricerca.

Ancora se torno alla ricerca generale Milano, riottengo i miei 3076 risultati e poi vado a selezionare in Ancient Findspot Aquileia trovo 66 risultati che non hanno nulla a che vedere con Milano. Tra l'altro il numero tra parentesi accanto al filtro Aquileia mi dice 67, invece ottengo 66 risultati.

Non capisco su che base agisca nella visualizzazione dei filtri disponibili perché se faccio una ricerca globale Aquileia ottengo 5144 risultati.

**Comment by cprando** [comment]
Fixed
