### ISSUE TITLE
New password if old is forgotten

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#25]
Altra cosa importante, non c'è un sistema per recuperare la password. Ho fatto le prove da Foggia e non ho dietro i miei dati per loggarmi, ho provato a registrare un nuovo account e mi dice mail già presente. Da nessuna parte trovo un modo per farmi rispedire la password se l'ho dimenticata.

da Silvia Evangelisti

**Comment by francescomambrini** [comment]
Password reset works now
