### ISSUE TITLE
Wrong item saved in the Archive

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#26]
I searched and saved the item with Trismegistos ID 202581.
When I go to my Archive and click on the button View, the item with title: "CEIPAC-24011-sello-1" is returned instead.
Consequently, the saved item is altogether NOT displayed (empty archive) in the EAGLE search mask of the Storytelling App (as if no items were saved in my archive).

**Comment by francescomambrini** [comment]
Same with the inscription TM-ID = 181253.
If I save it and click on "View" I get another item from "EPNet, Economic & Political Network". Is it related to the items from this CP?

**Comment by francescomambrini** [comment]
It works now

**Comment by cprando** [comment]
Indeed, this has just been fixed. Thanks Francesco.
