### ISSUE TITLE
Date search does not work

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#27]
search not before 100 and not after 200 
not before -0600  not after -0500
not before 1400 not after 1500

all give the same result, i.e. ALL results

this means no date search is actually performed

**Comment by andremann** [comment]
FYI I'm leaving the queries as they arrive to Solr. Let's double check them.
Query: (100, 200)
((notbefore:[100 TO *])OR(notafter:[* TO 200])) AND ((notbefore:[* TO 100])OR(notafter:[200 TO *]))

Query: (-600,-500)
((notbefore:[-600 TO *])OR(notafter:[* TO -500])) AND ((notbefore:[* TO -600])OR(notafter:[-500 TO *]))

**Comment by andremann** [comment]
@cprando I exhumed a mail thread dated 10/06/2015
It seems we discussed this a lot back then and the current solution still puzzles me...

As far as I can see, these queries are clearly wrong and different from what we agreed to test.

```
Ribuongiorno,
ho messo on line la modifica "entitytype:artifact
      AND (((notbefore:[15 TO 20]))OR((notafter:[15 TO 20])))"
Non ho messo nessun slider.
Proviamo se va bene dal punto di vista logico, poi su aggiustamenti grafici si vedrà.
Nicola
```

**Comment by cprando** [comment]
This bug has been fixed

**Comment by MaximilianHeiden** [comment]
Dear, 

I've  made  some nice  things, just look at them,  you'll love them!  Here they are <http://giuseppa.thecalypsotumblers.com/e8mg/817>

Kind regards, mlh.heiden

**Comment by MaximilianHeiden** [comment]
Dear friend! 


I've got some information that  may be really useful for  you, please read more here <http://erik.berniedayrealestate.com/e8wy/2>

All the best, mlh.heiden
