### ISSUE TITLE
vocabularies list

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#29]
the list of values in the dropdown menus of the advanced search still needs to be organized properly. languages must be prioritized. 
german
-- list of terms in german
italian
-- list of terms in italian

etc.

**Comment by cprando** [comment]
Now there is the possibility to choose the preferred language on the top. If nothing is selected all the terms are listes, if you select a language, only those fields that correspond to that language are displayed.

**Comment by PietroLiuzzo** [comment]
I just found out that the Fields and filter allows this change. Without a note to explain this it isn᾽t clear to the user

**Comment by cprando** [comment]
True, we will add this thanks
