### ISSUE TITLE
search layout

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#30]
the layout of the search is quite crazy. going in and out from advanced and basic search everything moves around and changes position

**Comment by PietroLiuzzo** [comment]
<img width="1069" alt="schermata 2016-02-29 alle 11 00 58" src="https://cloud.githubusercontent.com/assets/508012/13392630/d0b91490-ded3-11e5-8ea6-6c332b1bca82.png">

**Comment by cprando** [comment]
Going through one page to another one has now been improved
