### ISSUE TITLE
button "browse all"

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#31]
in basi search the button should read "search all"

**Comment by cprando** [comment]
Are you sure? We have been told explicitly to use "Browse all".
I add Francesco too. Let us know what to do.

**Comment by PietroLiuzzo** [comment]
the browse function (an organized list of contents which one can read and
navigate) it in my opinion different from a search function. that button is
running the query with the selected term, so imho is searching all, not
browsing

On 29 February 2016 at 11:45, cprando notifications@github.com wrote:

> Are you sure? We have been told explicitly to use "Browse all".
> I add Francesco too. Let us know what to do.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EAGLE-BPN/Inscription-Search-Engine/issues/31#issuecomment-190174330
> .

## 

Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by cprando** [comment]
To summarise how the basic search works:
1. you want to run a query with a specific keyword -> you enter your keyword in the text field (either directly or using the greek keyboard) and then press "Enter" in your keyboard or click on the lens which is on the field
2. you want to browse all the collections -> you click on "Browse All", a query is done on the whole DB and you can then browse/refine it using the facets

How can make this clearere to the user? Maybe adding a "Search button", or renaming the "Browse all" button, or again changing the Browse All button into something else (e.g. a link)?

**Comment by PietroLiuzzo** [comment]
could be something like "press ENTER to search OR _browse all_"

On 29 February 2016 at 13:18, cprando notifications@github.com wrote:

> To summarise how it works the basic search:
> 
>    1.
> 
>    you want to run a query with a specific keyword -> you enter your
>    keyword in the text field (either directly or using the greek keyboard) and
>    then press "Enter" in your keyboard or click on the lens which is on the
>    field
>    2.
> 
>    you want to browse all the collections -> you click on "Browse All", a
>    query is done on the whole DB and you can then browse/refine it using the
>    facets
> 
> How can make this clearere to the user? Maybe adding a "Search button", or
> renaming the "Browse all" button, or again changing the Browse All button
> into something else (e.g. a link)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EAGLE-BPN/Inscription-Search-Engine/issues/31#issuecomment-190208503
> .

## 

Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by cprando** [comment]
Uhm, yep we could also add something more, e.g.

Type a keyword and press ENTER, or browse all the EAGLE collections

Where "browse all the EAGLE collections" is a link to browse all

**Comment by francescomambrini** [comment]
This seems to be closed now!
