### ISSUE TITLE
view related inscription

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#34]
on selecting view related inscription before selecting the kind of relation to the present inscription the browser goes back to top of the page

**Comment by PietroLiuzzo** [comment]
on selecting a value where no relation is possible all results are returned instead of none. 

test searched CIL 02, 000087, clicked on the first result from EDCS, searched related inscriptions based on decoration. expected result none. obtained result: all.

**Comment by cprando** [comment]
This bug has been fixed

**Comment by MaximilianHeiden** [comment]
Hello, 

I've just seen something really weird and  I decided to ask you whether that is real or not. Just take a look <http://compare.thesynics.com/e8fvx/59>


Best wishes, mlh.heiden
