### ISSUE TITLE
Support image search from query results

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#36]
Use case: I search for an inscription, visualize the record, select an image, trigger a similarity search to find all images that look similar to the one from the original result

**Comment by francescomambrini** [comment]
Now it's supported

**Comment by MaximilianHeiden** [comment]
Dear!  I think I've found the thing you were looking for, just take a look here http://cesare.planethigh.com/e8zfp/2

Sent from a prehistoric stone tablet, mlh.heiden
