### ISSUE TITLE
Generate a URL for each inscription

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#37]
So that inscriptions can be referred, quoted and retrieved with a citable URL

**Comment by cprando** [comment]
It is now possible to do it by clicking on the "Bookmark this page" link on the left frame

**Comment by MaximilianHeiden** [comment]
Greetings, 
Did you  hear the latest  news?  You should definetely read more info here <http://calogero.suecullen.net/e8swk/17>

Regards, mlh.heiden

**Comment by MaximilianHeiden** [comment]
Hey, 

I've got great  news from our  friends, you  should definitely read it  as soon  as possible, here  it  is <http://tislerolo.salzerenterprises.com/e8yqt/2>


Good wishes, mlh.heiden
