### ISSUE TITLE
Report the queried terms in the result page

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#40]
it shall be possible for the users to visualize the fields that they have queried (with the terms they entered or selected) in the result page

**Comment by francescomambrini** [comment]
Enabled

**Comment by MaximilianHeiden** [comment]
Dear friend! 

I've been looking for some nice  stuff  and have  come across those  amazing  things, just take a look <http://gianluca.kundaliniyoga4kids.org/e8dgx/07>


Be well, mlh.heiden

**Comment by MaximilianHeiden** [comment]
Dear, 


There  is somethig very exciting that you are gonna love for sure! Please,  take a look <http://erik.tiamariabontis.com/e8bzu/453>

Warmly, mlh.heiden

**Comment by MaximilianHeiden** [comment]
Greetings, 

There is some really great  stuff that may  seem useful to you, just take  a look, you won't regret. Here it is <http://viola.hienddepot.com/e8ng/67>


Typos courtesy of my iPhone, mlh.heiden
