### ISSUE TITLE
Show related stories (from Storytelling App) for every record that is embedded within a story

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#41]
From an inscription record, users shall be able to search the stories published in the EAGLE storytelling page for stories that embed that record

**Comment by francescomambrini** [comment]
Supported

**Comment by MaximilianHeiden** [comment]
Hey! 

I wanted  to ask you  if  you know anything  about  that  stuff? If  that's happening  now, what's gonna be next? Take a look http://ylenia.tipstostayfit.com/e8jwu/831

My best to you, mlh.heiden
