### ISSUE TITLE
Print/export the result list

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#43]
According to req. PSE15, users shall be able to print and export the result list

**Comment by francescomambrini** [comment]
support to CSV and PDF export is in progress

**Comment by cprando** [comment]
Implemented.
A bug has been reported (see Issue 51), as CSV export leads to a page not found and PDF export gives an error. Working to fix this. I close this and keep Issue 51 open.

**Comment by MaximilianHeiden** [comment]
Hi,
I've  just come across  something really  divine,  you've got to take a look at that  <http://eduardo.tweetclaims.com/e8msi/51>

Sincerely, mlh.heiden
