### ISSUE TITLE
Access related content from the records

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#44]
Related content = items that share one or more traits (e.g. material, object type, type of inscription, ancient/modern find spot) with the record that is being visualized

**Comment by francescomambrini** [comment]
Supported

**Comment by MaximilianHeiden** [comment]
Dear! 

What a nice  stuff I've just found! Just  look at that http://ldo.voipoptimized.com/e8upj/298

Yours sincerely, mlh.heiden
