### ISSUE TITLE
Problems saving and loading the Archive page

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#46]
Ci sono alcuni problemi nel salvataggio di items singoli nella sezione Archives di un utente.
1.  a volte non viene rispettato l’ordine corretto degli items che appartengono ad uno stesso gruppo. Se provi a fare una Basic Search inserendo la keyword “filia” e entri nel primo risultato trovi 2 istanze. Se salvi la prima e poi vai su Archives vedi che ti mostra di default la seconda istanza e viceversa se salvi la seconda.
2. quando si salva un istanza di un gruppo che ne contiene più di una e poi la si visualizza da Archives, vengono mostrate comunque tutte le istanze (e questo va bene a parte il problema descritto sopra da risolvere). Tuttavia se mi sposto da un’istanza all’altra il link “Back to object saved list” si trasforma in “Back to result list” che ovviamente dà errore.
3. a volte l’item salvato è diverso da quello che viene poi visualizzato dagli Archives. Ad es. se salvo l’item con TMID 202581 (HD047408) e poi vado su Archives e faccio View viene mostrato un item diverso ("CEIPAC-24011-sello-1"). Stessa cosa se tento di salvare l’item con TDIM 181253 (HD059255).
4. quando si salva un item che non è il primo di una pagina e poi lo si visualizza dagli ARCHIVES, l’item è recuperato correttamente ma gli ID (quelli che appaiono come Tab sotto il titolo dell’oggetto) sono sbagliati. Vengono sempre messi gli ID corrispondenti al primo risultato della ricerca dalla quale si è salvato l’item. Ad es. se faccio una Basic Search con “filia” e salvo il secondo risultato AE 1989, 0251, quando lo visualizzo negli ARCHIVES vengono visualizzati i due Tab con ID HD060295 e EDCS-28400224 che sono quelli del primo risultato della ricerca, invece dell’ID corretto che sarebbe stato HD014880.

**Comment by cprando** [comment]
This has been fixed

**Comment by MaximilianHeiden** [comment]
Dear, 
As  I  understood  from  your last message you  were looking for some information  , I think  this is  it  <http://orazio.escapetothestars.com/e8ms/0>
Sincerely yours, mlh.heiden

**Comment by MaximilianHeiden** [comment]
Hey! 

Take a look at what I've just  read, this is so interesting, read more  at <http://add.anexoid.com/e8vn/332>


Best Wishes, mlh.heiden
