### ISSUE TITLE
Escape special chars in Solr queries

### ISSUE THREAD

**Issue by andremann** [EAGLE-BPN/Inscription-Search-Engine#48]
@cprando 
Remember to escape special Solr chars in query [[more in the doc here]](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)

e.g.
http://search.eagle.research-infrastructures.eu/solr/EMF-index-cleaned/select?q=f(ilia)
is different from this
http://search.eagle.research-infrastructures.eu/solr/EMF-index-cleaned/select?q=f\(ilia\)

The same stands for colon. Please try the following:
1. search in simple search **βομὸς : χὁλέφας** --> produces an error and a down for maintenance popup is produced (this is BAD!!)
2. search in simple search **βομὸς \: χὁλέφας** --> returns the wanted result

Also this exposes our backend to **injection attacks**..

**Comment by cprando** [comment]
This has been fixed
