### ISSUE TITLE
[advanced search] Add/remove field: confusing behaviour

### ISSUE THREAD

**Issue by andremann** [EAGLE-BPN/Inscription-Search-Engine#49]
When you check more than on field on the left menu and click "update search form" not all the fields are added properly.
@cprando Why so?

e.g. 
1. check "location" and "detailed findspot", click update. only "location" field is added.
2.check "material", "decoration" and "state of preservation", click update. only "state of preservation is added"

**Comment by cprando** [comment]
It was a bug. Fixed now.
