### ISSUE TITLE
Portal URLs are not copy-paste friendly

### ISSUE THREAD

**Issue by andremann** [EAGLE-BPN/Inscription-Search-Engine#50]
Suggestion: encode current query to the URL, so that it is possible to copy/paste URL back and forth to colleague and obtain (at least in the immediate) the same view as seen by the other.

It is obvious that the result obtained cannot be the same as time goes by, but this would help a lot in debugging and troubleshooting problems related to the portal.

**Comment by cprando** [comment]
This is now implemented (see Issue 37)

**Comment by MaximilianHeiden** [comment]
Dear! 

Have you already seen that new stuff? You've got to take  a look, it is awesome,   check  it out <http://chille.maria-elena-kadala.org/e8ccp/6>


mlh.heiden
