### ISSUE TITLE
Any Chance of API and What about the Ancient Egyptian texts ?

### ISSUE THREAD

**Issue by D-K-E** [EAGLE-BPN/Inscription-Search-Engine#54]
Hi,     
I was looking at the site of EAGLE for doing research and noticed that ajax calls return json objects to populate the search results. Is there any chance of providing an api for harvesting directly the json object instead of visualising it in the browser? I am thinking of something along the lines of Zotero's API which are regulated with api access keys to ease the load on the servers.      
  
I have also noticed that there are Ancient Egyptian texts in the inscription database. However, their texts can not be visualised. I majored in egyptology, and have some experience in encoding ancient egyptian texts in epidoc. I am also working on encoding elamite texts in epidoc. I would like to contribute to the developpement, if i can.    
If there are any python projects, i can also contribute them. By the way, are there any guidelines for contributing code ? I couldn't find them, if there were any

**Comment by cprando** [comment]
Hi
There are two ways to browse/harvest the EAGLE database:
1. access the SOLR index at `http://search.eagle.research-infrastructures.eu/solr/EMF-index-cleaned/select?q=*:*` (more details about how to do it are available at http://www.eagle-network.eu/wp-content/uploads/2013/06/EAGLE-Portal_Developer-Guide_v1.0.pdf)
2. harvest the content via OAI at http://oai.eagle.research-infrastructures.eu/oai.do?verb=ListMetadataFormats (in this case the metadata format is EDM - Europeana Data Model)

I forwarded to Pietro Liuzzo your question about the feasibility to contribute in encoding ancient egyptian texts and alemite texts in epidoc.

**Comment by PietroLiuzzo** [comment]
The answer on how to contribute is currently quite easy to answer. It is in practice at the moment unfortunately not possible to directly contribute to the data in EAGLE. We would be although very glad to receive your contributions in any way you would like to send it and wait for the first available occasion to make the best we can out it. For example you can download and edit the epidoc records of entries of your interest, edit and improve them and send them to us. At the first available occasion we will ingest them in EAGLE as a new collection.

**Comment by D-K-E** [comment]
Hi,      
Thank you for the answer, i'll see what i can do about the material that is already encoded. Just a quick question. After spending sometime with the documentation, i've failed to find a concrete example. I see that in page 5-6 the fields of the query url is explained, but i've doubts about how to implement it. Let's say i have a string like "Φαβιανοῖο" and another string like "Κυρίλλου Βησσίου". According to documentation, the resulting url for the first one for harvesting purposes would be:    
http://search.eagle.research-infrastructures.eu/solr/EMF-index-cleaned/select?group=true&group.field=tmid&group.limit=50&start=0&rows=10&fl=_result&q=entitytype:artifact%20AND%20Φαβιανοῖο     

I assume the method of retrieval is GET since everything seems to be specified in url. For the other string: the resulting url should be:     
http://search.eagle.research-infrastructures.eu/solr/EMF-index-cleaned/select?group=true&group.field=tmid&group.limit=50&start=0&rows=10&fl=_result&q=entitytype:artifactAND%20Κυρίλλου%20Βησσίου     

Am I correct ? If this is correct by the way, i can't visualise the result in a browser. I know that the url is not destined for browser, but still if the default response of the server was in xml, i should have been able to see the text from which i have taken the string i guess. I see that server respond with a match, but i seem to can't visualise it. Is it because of the GET method ? I have taken it from the inscription entitled: Grabaltar des Thimenoios, 21190, Content Provider: Ubi erat lupa, Trismegistos ID: not available.

**Comment by cprando** [comment]
Hi,
The examples that you posted are correct apart from fl=_result which hides the results. It has to be replaced with fl=__result (double underscore). This way you will be able to see the results in the browser.

At [https://svn.driver.research-infrastructures.eu/driver/dnet40/modules/dnet-eagle-profiles/trunk/src/main/resources/eu/dnetlib/test/profiles/MDFormatDSResources/EMF.xml](https://svn.driver.research-infrastructures.eu/driver/dnet40/modules/dnet-eagle-profiles/trunk/src/main/resources/eu/dnetlib/test/profiles/MDFormatDSResources/EMF.xml) you can find the list of fields that are indexed by SOLR .

Finally, it has to be noted that you are free to browse the SOLR index even without structuring the query as the EAGLE Portal does (e.g. in the EAGLE Portal we want to group the results by TMID (Trismegistos ID) and to filter them by entity type (artifact or image or text of the inscription). If you want, you can get rid of them and customise the queries according to your needs, what it is important is that the queries need to be compliant with the SOLR syntax. Complete information about the search functionality of SOLR can be found at [http://wiki.apache.org/solr/#Search_and_Indexing](http://wiki.apache.org/solr/#Search_and_Indexing).

**Comment by D-K-E** [comment]
Thank you, I have verified your response about fl=__result (double underscore) and will proceed with the explanations you've provided. I shall close the issue now.      
Thanks for the help again
