### ISSUE TITLE
registering in advanced search not possible

### ISSUE THREAD

**Issue by wenamun** [EAGLE-BPN/Inscription-Search-Engine#7]
entering all information in the register dialog results in the message:

> User added! You must to be approved to get your password at you email address.
1. the English text of the message should be corrected
2. after that the process stops, there is no password sent to the newly registered user, so it's impossible to use any of the advanced features of EAGLE search.

**Comment by cprando** [comment]
1. yes, the English needs to be definitely corrected in: "Thank you for your registration, your request has been forwarded to the site administrator. As soon as he approves it, an email containing your password will be sent to the email address that you have specified in the registration request."
2. currently the approval is manual and therefore it might take some time before I can approve the requests. Now I have approved you so you can try the advanced features.
